from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class CapabilityKV(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, value=None):  # noqa: E501
        """CapabilityKV - a model defined in OpenAPI

        :param type: The type of this CapabilityKV.  # noqa: E501
        :type type: str
        :param value: The value of this CapabilityKV.  # noqa: E501
        :type value: str
        """
        self.openapi_types = {
            'type': str,
            'value': str
        }

        self.attribute_map = {
            'type': 'type',
            'value': 'value'
        }

        self._type = type
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'CapabilityKV':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CapabilityKV of this CapabilityKV.  # noqa: E501
        :rtype: CapabilityKV
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this CapabilityKV.

        One of mon|osd|mds|mgr  # noqa: E501

        :return: The type of this CapabilityKV.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this CapabilityKV.

        One of mon|osd|mds|mgr  # noqa: E501

        :param type: The type of this CapabilityKV.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def value(self) -> str:
        """Gets the value of this CapabilityKV.

        Capability string, e.g. `allow rw`, `allow r fsname=CEPH-FS-01 path=/volumes/_nogroup/demo`  # noqa: E501

        :return: The value of this CapabilityKV.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this CapabilityKV.

        Capability string, e.g. `allow rw`, `allow r fsname=CEPH-FS-01 path=/volumes/_nogroup/demo`  # noqa: E501

        :param value: The value of this CapabilityKV.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
