from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class CreateS3BucketRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bucket=None, uid=None, placement_rule=None, versioning='Disabled'):  # noqa: E501
        """CreateS3BucketRequest - a model defined in OpenAPI

        :param bucket: The bucket of this CreateS3BucketRequest.  # noqa: E501
        :type bucket: str
        :param uid: The uid of this CreateS3BucketRequest.  # noqa: E501
        :type uid: str
        :param placement_rule: The placement_rule of this CreateS3BucketRequest.  # noqa: E501
        :type placement_rule: str
        :param versioning: The versioning of this CreateS3BucketRequest.  # noqa: E501
        :type versioning: str
        """
        self.openapi_types = {
            'bucket': str,
            'uid': str,
            'placement_rule': str,
            'versioning': str
        }

        self.attribute_map = {
            'bucket': 'bucket',
            'uid': 'uid',
            'placement_rule': 'placement_rule',
            'versioning': 'versioning'
        }

        self._bucket = bucket
        self._uid = uid
        self._placement_rule = placement_rule
        self._versioning = versioning

    @classmethod
    def from_dict(cls, dikt) -> 'CreateS3BucketRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateS3BucketRequest of this CreateS3BucketRequest.  # noqa: E501
        :rtype: CreateS3BucketRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bucket(self) -> str:
        """Gets the bucket of this CreateS3BucketRequest.


        :return: The bucket of this CreateS3BucketRequest.
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket: str):
        """Sets the bucket of this CreateS3BucketRequest.


        :param bucket: The bucket of this CreateS3BucketRequest.
        :type bucket: str
        """
        if bucket is None:
            raise ValueError("Invalid value for `bucket`, must not be `None`")  # noqa: E501

        self._bucket = bucket

    @property
    def uid(self) -> str:
        """Gets the uid of this CreateS3BucketRequest.

        Owner uid  # noqa: E501

        :return: The uid of this CreateS3BucketRequest.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this CreateS3BucketRequest.

        Owner uid  # noqa: E501

        :param uid: The uid of this CreateS3BucketRequest.
        :type uid: str
        """
        if uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    @property
    def placement_rule(self) -> str:
        """Gets the placement_rule of this CreateS3BucketRequest.


        :return: The placement_rule of this CreateS3BucketRequest.
        :rtype: str
        """
        return self._placement_rule

    @placement_rule.setter
    def placement_rule(self, placement_rule: str):
        """Sets the placement_rule of this CreateS3BucketRequest.


        :param placement_rule: The placement_rule of this CreateS3BucketRequest.
        :type placement_rule: str
        """

        self._placement_rule = placement_rule

    @property
    def versioning(self) -> str:
        """Gets the versioning of this CreateS3BucketRequest.


        :return: The versioning of this CreateS3BucketRequest.
        :rtype: str
        """
        return self._versioning

    @versioning.setter
    def versioning(self, versioning: str):
        """Sets the versioning of this CreateS3BucketRequest.


        :param versioning: The versioning of this CreateS3BucketRequest.
        :type versioning: str
        """
        allowed_values = ["Enabled", "Suspended", "Disabled"]  # noqa: E501
        if versioning not in allowed_values:
            raise ValueError(
                "Invalid value for `versioning` ({0}), must be one of {1}"
                .format(versioning, allowed_values)
            )

        self._versioning = versioning
