from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class CreateS3KeyRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, access_key=None, secret_key=None, generate=True):  # noqa: E501
        """CreateS3KeyRequest - a model defined in OpenAPI

        :param access_key: The access_key of this CreateS3KeyRequest.  # noqa: E501
        :type access_key: str
        :param secret_key: The secret_key of this CreateS3KeyRequest.  # noqa: E501
        :type secret_key: str
        :param generate: The generate of this CreateS3KeyRequest.  # noqa: E501
        :type generate: bool
        """
        self.openapi_types = {
            'access_key': str,
            'secret_key': str,
            'generate': bool
        }

        self.attribute_map = {
            'access_key': 'access_key',
            'secret_key': 'secret_key',
            'generate': 'generate'
        }

        self._access_key = access_key
        self._secret_key = secret_key
        self._generate = generate

    @classmethod
    def from_dict(cls, dikt) -> 'CreateS3KeyRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateS3KeyRequest of this CreateS3KeyRequest.  # noqa: E501
        :rtype: CreateS3KeyRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_key(self) -> str:
        """Gets the access_key of this CreateS3KeyRequest.


        :return: The access_key of this CreateS3KeyRequest.
        :rtype: str
        """
        return self._access_key

    @access_key.setter
    def access_key(self, access_key: str):
        """Sets the access_key of this CreateS3KeyRequest.


        :param access_key: The access_key of this CreateS3KeyRequest.
        :type access_key: str
        """

        self._access_key = access_key

    @property
    def secret_key(self) -> str:
        """Gets the secret_key of this CreateS3KeyRequest.


        :return: The secret_key of this CreateS3KeyRequest.
        :rtype: str
        """
        return self._secret_key

    @secret_key.setter
    def secret_key(self, secret_key: str):
        """Sets the secret_key of this CreateS3KeyRequest.


        :param secret_key: The secret_key of this CreateS3KeyRequest.
        :type secret_key: str
        """

        self._secret_key = secret_key

    @property
    def generate(self) -> bool:
        """Gets the generate of this CreateS3KeyRequest.


        :return: The generate of this CreateS3KeyRequest.
        :rtype: bool
        """
        return self._generate

    @generate.setter
    def generate(self, generate: bool):
        """Sets the generate of this CreateS3KeyRequest.


        :param generate: The generate of this CreateS3KeyRequest.
        :type generate: bool
        """

        self._generate = generate
