from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server.models.create_or_update_s3_user_request_caps_inner import CreateOrUpdateS3UserRequestCapsInner
from fabric_ceph.openapi_server.models.create_s3_key_request import CreateS3KeyRequest
from fabric_ceph.openapi_server import util

from fabric_ceph.openapi_server.models.create_or_update_s3_user_request_caps_inner import CreateOrUpdateS3UserRequestCapsInner  # noqa: E501
from fabric_ceph.openapi_server.models.create_s3_key_request import CreateS3KeyRequest  # noqa: E501

class CreateOrUpdateS3UserRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uid=None, display_name=None, email=None, suspended=False, max_buckets=1000, system=False, op_mask=None, caps=None, keys=None):  # noqa: E501
        """CreateOrUpdateS3UserRequest - a model defined in OpenAPI

        :param uid: The uid of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type uid: str
        :param display_name: The display_name of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type display_name: str
        :param email: The email of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type email: str
        :param suspended: The suspended of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type suspended: bool
        :param max_buckets: The max_buckets of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type max_buckets: int
        :param system: The system of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type system: bool
        :param op_mask: The op_mask of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type op_mask: str
        :param caps: The caps of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type caps: List[CreateOrUpdateS3UserRequestCapsInner]
        :param keys: The keys of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :type keys: List[CreateS3KeyRequest]
        """
        self.openapi_types = {
            'uid': str,
            'display_name': str,
            'email': str,
            'suspended': bool,
            'max_buckets': int,
            'system': bool,
            'op_mask': str,
            'caps': List[CreateOrUpdateS3UserRequestCapsInner],
            'keys': List[CreateS3KeyRequest]
        }

        self.attribute_map = {
            'uid': 'uid',
            'display_name': 'display_name',
            'email': 'email',
            'suspended': 'suspended',
            'max_buckets': 'max_buckets',
            'system': 'system',
            'op_mask': 'op_mask',
            'caps': 'caps',
            'keys': 'keys'
        }

        self._uid = uid
        self._display_name = display_name
        self._email = email
        self._suspended = suspended
        self._max_buckets = max_buckets
        self._system = system
        self._op_mask = op_mask
        self._caps = caps
        self._keys = keys

    @classmethod
    def from_dict(cls, dikt) -> 'CreateOrUpdateS3UserRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateOrUpdateS3UserRequest of this CreateOrUpdateS3UserRequest.  # noqa: E501
        :rtype: CreateOrUpdateS3UserRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> str:
        """Gets the uid of this CreateOrUpdateS3UserRequest.


        :return: The uid of this CreateOrUpdateS3UserRequest.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this CreateOrUpdateS3UserRequest.


        :param uid: The uid of this CreateOrUpdateS3UserRequest.
        :type uid: str
        """
        if uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    @property
    def display_name(self) -> str:
        """Gets the display_name of this CreateOrUpdateS3UserRequest.


        :return: The display_name of this CreateOrUpdateS3UserRequest.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this CreateOrUpdateS3UserRequest.


        :param display_name: The display_name of this CreateOrUpdateS3UserRequest.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def email(self) -> str:
        """Gets the email of this CreateOrUpdateS3UserRequest.


        :return: The email of this CreateOrUpdateS3UserRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this CreateOrUpdateS3UserRequest.


        :param email: The email of this CreateOrUpdateS3UserRequest.
        :type email: str
        """

        self._email = email

    @property
    def suspended(self) -> bool:
        """Gets the suspended of this CreateOrUpdateS3UserRequest.


        :return: The suspended of this CreateOrUpdateS3UserRequest.
        :rtype: bool
        """
        return self._suspended

    @suspended.setter
    def suspended(self, suspended: bool):
        """Sets the suspended of this CreateOrUpdateS3UserRequest.


        :param suspended: The suspended of this CreateOrUpdateS3UserRequest.
        :type suspended: bool
        """

        self._suspended = suspended

    @property
    def max_buckets(self) -> int:
        """Gets the max_buckets of this CreateOrUpdateS3UserRequest.


        :return: The max_buckets of this CreateOrUpdateS3UserRequest.
        :rtype: int
        """
        return self._max_buckets

    @max_buckets.setter
    def max_buckets(self, max_buckets: int):
        """Sets the max_buckets of this CreateOrUpdateS3UserRequest.


        :param max_buckets: The max_buckets of this CreateOrUpdateS3UserRequest.
        :type max_buckets: int
        """

        self._max_buckets = max_buckets

    @property
    def system(self) -> bool:
        """Gets the system of this CreateOrUpdateS3UserRequest.


        :return: The system of this CreateOrUpdateS3UserRequest.
        :rtype: bool
        """
        return self._system

    @system.setter
    def system(self, system: bool):
        """Sets the system of this CreateOrUpdateS3UserRequest.


        :param system: The system of this CreateOrUpdateS3UserRequest.
        :type system: bool
        """

        self._system = system

    @property
    def op_mask(self) -> str:
        """Gets the op_mask of this CreateOrUpdateS3UserRequest.


        :return: The op_mask of this CreateOrUpdateS3UserRequest.
        :rtype: str
        """
        return self._op_mask

    @op_mask.setter
    def op_mask(self, op_mask: str):
        """Sets the op_mask of this CreateOrUpdateS3UserRequest.


        :param op_mask: The op_mask of this CreateOrUpdateS3UserRequest.
        :type op_mask: str
        """

        self._op_mask = op_mask

    @property
    def caps(self) -> List[CreateOrUpdateS3UserRequestCapsInner]:
        """Gets the caps of this CreateOrUpdateS3UserRequest.


        :return: The caps of this CreateOrUpdateS3UserRequest.
        :rtype: List[CreateOrUpdateS3UserRequestCapsInner]
        """
        return self._caps

    @caps.setter
    def caps(self, caps: List[CreateOrUpdateS3UserRequestCapsInner]):
        """Sets the caps of this CreateOrUpdateS3UserRequest.


        :param caps: The caps of this CreateOrUpdateS3UserRequest.
        :type caps: List[CreateOrUpdateS3UserRequestCapsInner]
        """

        self._caps = caps

    @property
    def keys(self) -> List[CreateS3KeyRequest]:
        """Gets the keys of this CreateOrUpdateS3UserRequest.

        Optional explicit keypairs to set; omit to auto-generate none.  # noqa: E501

        :return: The keys of this CreateOrUpdateS3UserRequest.
        :rtype: List[CreateS3KeyRequest]
        """
        return self._keys

    @keys.setter
    def keys(self, keys: List[CreateS3KeyRequest]):
        """Sets the keys of this CreateOrUpdateS3UserRequest.

        Optional explicit keypairs to set; omit to auto-generate none.  # noqa: E501

        :param keys: The keys of this CreateOrUpdateS3UserRequest.
        :type keys: List[CreateS3KeyRequest]
        """

        self._keys = keys
