from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class ExportUsers200ResponseOneOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, keyring=None):  # noqa: E501
        """ExportUsers200ResponseOneOf - a model defined in OpenAPI

        :param keyring: The keyring of this ExportUsers200ResponseOneOf.  # noqa: E501
        :type keyring: str
        """
        self.openapi_types = {
            'keyring': str
        }

        self.attribute_map = {
            'keyring': 'keyring'
        }

        self._keyring = keyring

    @classmethod
    def from_dict(cls, dikt) -> 'ExportUsers200ResponseOneOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The exportUsers_200_response_oneOf of this ExportUsers200ResponseOneOf.  # noqa: E501
        :rtype: ExportUsers200ResponseOneOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def keyring(self) -> str:
        """Gets the keyring of this ExportUsers200ResponseOneOf.


        :return: The keyring of this ExportUsers200ResponseOneOf.
        :rtype: str
        """
        return self._keyring

    @keyring.setter
    def keyring(self, keyring: str):
        """Sets the keyring of this ExportUsers200ResponseOneOf.


        :param keyring: The keyring of this ExportUsers200ResponseOneOf.
        :type keyring: str
        """

        self._keyring = keyring
