from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server.models.export_users200_response_one_of import ExportUsers200ResponseOneOf
from fabric_ceph.openapi_server import util

from fabric_ceph.openapi_server.models.export_users200_response_one_of import ExportUsers200ResponseOneOf  # noqa: E501

class KeyringsAllOfData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, keyring=None):  # noqa: E501
        """KeyringsAllOfData - a model defined in OpenAPI

        :param keyring: The keyring of this KeyringsAllOfData.  # noqa: E501
        :type keyring: str
        """
        self.openapi_types = {
            'keyring': str
        }

        self.attribute_map = {
            'keyring': 'keyring'
        }

        self._keyring = keyring

    @classmethod
    def from_dict(cls, dikt) -> 'KeyringsAllOfData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The keyrings_allOf_data of this KeyringsAllOfData.  # noqa: E501
        :rtype: KeyringsAllOfData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def keyring(self) -> str:
        """Gets the keyring of this KeyringsAllOfData.


        :return: The keyring of this KeyringsAllOfData.
        :rtype: str
        """
        return self._keyring

    @keyring.setter
    def keyring(self, keyring: str):
        """Sets the keyring of this KeyringsAllOfData.


        :param keyring: The keyring of this KeyringsAllOfData.
        :type keyring: str
        """

        self._keyring = keyring
