from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server.models.s3_acl_grants_inner import S3AclGrantsInner
from fabric_ceph.openapi_server import util

from fabric_ceph.openapi_server.models.s3_acl_grants_inner import S3AclGrantsInner  # noqa: E501

class S3Acl(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, canned=None, grants=None):  # noqa: E501
        """S3Acl - a model defined in OpenAPI

        :param canned: The canned of this S3Acl.  # noqa: E501
        :type canned: str
        :param grants: The grants of this S3Acl.  # noqa: E501
        :type grants: List[S3AclGrantsInner]
        """
        self.openapi_types = {
            'canned': str,
            'grants': List[S3AclGrantsInner]
        }

        self.attribute_map = {
            'canned': 'canned',
            'grants': 'grants'
        }

        self._canned = canned
        self._grants = grants

    @classmethod
    def from_dict(cls, dikt) -> 'S3Acl':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3Acl of this S3Acl.  # noqa: E501
        :rtype: S3Acl
        """
        return util.deserialize_model(dikt, cls)

    @property
    def canned(self) -> str:
        """Gets the canned of this S3Acl.

        One of private|public-read|public-read-write|authenticated-read  # noqa: E501

        :return: The canned of this S3Acl.
        :rtype: str
        """
        return self._canned

    @canned.setter
    def canned(self, canned: str):
        """Sets the canned of this S3Acl.

        One of private|public-read|public-read-write|authenticated-read  # noqa: E501

        :param canned: The canned of this S3Acl.
        :type canned: str
        """

        self._canned = canned

    @property
    def grants(self) -> List[S3AclGrantsInner]:
        """Gets the grants of this S3Acl.


        :return: The grants of this S3Acl.
        :rtype: List[S3AclGrantsInner]
        """
        return self._grants

    @grants.setter
    def grants(self, grants: List[S3AclGrantsInner]):
        """Sets the grants of this S3Acl.


        :param grants: The grants of this S3Acl.
        :type grants: List[S3AclGrantsInner]
        """

        self._grants = grants
