from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class S3AclGrantsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, grantee=None, permission=None):  # noqa: E501
        """S3AclGrantsInner - a model defined in OpenAPI

        :param grantee: The grantee of this S3AclGrantsInner.  # noqa: E501
        :type grantee: str
        :param permission: The permission of this S3AclGrantsInner.  # noqa: E501
        :type permission: str
        """
        self.openapi_types = {
            'grantee': str,
            'permission': str
        }

        self.attribute_map = {
            'grantee': 'grantee',
            'permission': 'permission'
        }

        self._grantee = grantee
        self._permission = permission

    @classmethod
    def from_dict(cls, dikt) -> 'S3AclGrantsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3Acl_grants_inner of this S3AclGrantsInner.  # noqa: E501
        :rtype: S3AclGrantsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def grantee(self) -> str:
        """Gets the grantee of this S3AclGrantsInner.


        :return: The grantee of this S3AclGrantsInner.
        :rtype: str
        """
        return self._grantee

    @grantee.setter
    def grantee(self, grantee: str):
        """Sets the grantee of this S3AclGrantsInner.


        :param grantee: The grantee of this S3AclGrantsInner.
        :type grantee: str
        """

        self._grantee = grantee

    @property
    def permission(self) -> str:
        """Gets the permission of this S3AclGrantsInner.


        :return: The permission of this S3AclGrantsInner.
        :rtype: str
        """
        return self._permission

    @permission.setter
    def permission(self, permission: str):
        """Sets the permission of this S3AclGrantsInner.


        :param permission: The permission of this S3AclGrantsInner.
        :type permission: str
        """

        self._permission = permission
