from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class S3BucketListAllOfData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, owner=None):  # noqa: E501
        """S3BucketListAllOfData - a model defined in OpenAPI

        :param name: The name of this S3BucketListAllOfData.  # noqa: E501
        :type name: str
        :param owner: The owner of this S3BucketListAllOfData.  # noqa: E501
        :type owner: str
        """
        self.openapi_types = {
            'name': str,
            'owner': str
        }

        self.attribute_map = {
            'name': 'name',
            'owner': 'owner'
        }

        self._name = name
        self._owner = owner

    @classmethod
    def from_dict(cls, dikt) -> 'S3BucketListAllOfData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3BucketList_allOf_data of this S3BucketListAllOfData.  # noqa: E501
        :rtype: S3BucketListAllOfData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this S3BucketListAllOfData.


        :return: The name of this S3BucketListAllOfData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this S3BucketListAllOfData.


        :param name: The name of this S3BucketListAllOfData.
        :type name: str
        """

        self._name = name

    @property
    def owner(self) -> str:
        """Gets the owner of this S3BucketListAllOfData.


        :return: The owner of this S3BucketListAllOfData.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner: str):
        """Sets the owner of this S3BucketListAllOfData.


        :param owner: The owner of this S3BucketListAllOfData.
        :type owner: str
        """

        self._owner = owner
