from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class S3Bucket(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, owner=None, num_objects=None, size_kb=None, placement_rule=None, zonegroup=None, zone=None, versioning=None):  # noqa: E501
        """S3Bucket - a model defined in OpenAPI

        :param name: The name of this S3Bucket.  # noqa: E501
        :type name: str
        :param owner: The owner of this S3Bucket.  # noqa: E501
        :type owner: str
        :param num_objects: The num_objects of this S3Bucket.  # noqa: E501
        :type num_objects: int
        :param size_kb: The size_kb of this S3Bucket.  # noqa: E501
        :type size_kb: int
        :param placement_rule: The placement_rule of this S3Bucket.  # noqa: E501
        :type placement_rule: str
        :param zonegroup: The zonegroup of this S3Bucket.  # noqa: E501
        :type zonegroup: str
        :param zone: The zone of this S3Bucket.  # noqa: E501
        :type zone: str
        :param versioning: The versioning of this S3Bucket.  # noqa: E501
        :type versioning: str
        """
        self.openapi_types = {
            'name': str,
            'owner': str,
            'num_objects': int,
            'size_kb': int,
            'placement_rule': str,
            'zonegroup': str,
            'zone': str,
            'versioning': str
        }

        self.attribute_map = {
            'name': 'name',
            'owner': 'owner',
            'num_objects': 'num_objects',
            'size_kb': 'size_kb',
            'placement_rule': 'placement_rule',
            'zonegroup': 'zonegroup',
            'zone': 'zone',
            'versioning': 'versioning'
        }

        self._name = name
        self._owner = owner
        self._num_objects = num_objects
        self._size_kb = size_kb
        self._placement_rule = placement_rule
        self._zonegroup = zonegroup
        self._zone = zone
        self._versioning = versioning

    @classmethod
    def from_dict(cls, dikt) -> 'S3Bucket':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3Bucket of this S3Bucket.  # noqa: E501
        :rtype: S3Bucket
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this S3Bucket.


        :return: The name of this S3Bucket.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this S3Bucket.


        :param name: The name of this S3Bucket.
        :type name: str
        """

        self._name = name

    @property
    def owner(self) -> str:
        """Gets the owner of this S3Bucket.


        :return: The owner of this S3Bucket.
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner: str):
        """Sets the owner of this S3Bucket.


        :param owner: The owner of this S3Bucket.
        :type owner: str
        """

        self._owner = owner

    @property
    def num_objects(self) -> int:
        """Gets the num_objects of this S3Bucket.


        :return: The num_objects of this S3Bucket.
        :rtype: int
        """
        return self._num_objects

    @num_objects.setter
    def num_objects(self, num_objects: int):
        """Sets the num_objects of this S3Bucket.


        :param num_objects: The num_objects of this S3Bucket.
        :type num_objects: int
        """

        self._num_objects = num_objects

    @property
    def size_kb(self) -> int:
        """Gets the size_kb of this S3Bucket.


        :return: The size_kb of this S3Bucket.
        :rtype: int
        """
        return self._size_kb

    @size_kb.setter
    def size_kb(self, size_kb: int):
        """Sets the size_kb of this S3Bucket.


        :param size_kb: The size_kb of this S3Bucket.
        :type size_kb: int
        """

        self._size_kb = size_kb

    @property
    def placement_rule(self) -> str:
        """Gets the placement_rule of this S3Bucket.


        :return: The placement_rule of this S3Bucket.
        :rtype: str
        """
        return self._placement_rule

    @placement_rule.setter
    def placement_rule(self, placement_rule: str):
        """Sets the placement_rule of this S3Bucket.


        :param placement_rule: The placement_rule of this S3Bucket.
        :type placement_rule: str
        """

        self._placement_rule = placement_rule

    @property
    def zonegroup(self) -> str:
        """Gets the zonegroup of this S3Bucket.


        :return: The zonegroup of this S3Bucket.
        :rtype: str
        """
        return self._zonegroup

    @zonegroup.setter
    def zonegroup(self, zonegroup: str):
        """Sets the zonegroup of this S3Bucket.


        :param zonegroup: The zonegroup of this S3Bucket.
        :type zonegroup: str
        """

        self._zonegroup = zonegroup

    @property
    def zone(self) -> str:
        """Gets the zone of this S3Bucket.


        :return: The zone of this S3Bucket.
        :rtype: str
        """
        return self._zone

    @zone.setter
    def zone(self, zone: str):
        """Sets the zone of this S3Bucket.


        :param zone: The zone of this S3Bucket.
        :type zone: str
        """

        self._zone = zone

    @property
    def versioning(self) -> str:
        """Gets the versioning of this S3Bucket.


        :return: The versioning of this S3Bucket.
        :rtype: str
        """
        return self._versioning

    @versioning.setter
    def versioning(self, versioning: str):
        """Sets the versioning of this S3Bucket.


        :param versioning: The versioning of this S3Bucket.
        :type versioning: str
        """
        allowed_values = ["Enabled", "Suspended", "Disabled"]  # noqa: E501
        if versioning not in allowed_values:
            raise ValueError(
                "Invalid value for `versioning` ({0}), must be one of {1}"
                .format(versioning, allowed_values)
            )

        self._versioning = versioning
