from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class S3BucketQuotaRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, enabled=True, max_size_kb=None, max_objects=None):  # noqa: E501
        """S3BucketQuotaRequest - a model defined in OpenAPI

        :param enabled: The enabled of this S3BucketQuotaRequest.  # noqa: E501
        :type enabled: bool
        :param max_size_kb: The max_size_kb of this S3BucketQuotaRequest.  # noqa: E501
        :type max_size_kb: int
        :param max_objects: The max_objects of this S3BucketQuotaRequest.  # noqa: E501
        :type max_objects: int
        """
        self.openapi_types = {
            'enabled': bool,
            'max_size_kb': int,
            'max_objects': int
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'max_size_kb': 'max_size_kb',
            'max_objects': 'max_objects'
        }

        self._enabled = enabled
        self._max_size_kb = max_size_kb
        self._max_objects = max_objects

    @classmethod
    def from_dict(cls, dikt) -> 'S3BucketQuotaRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3BucketQuotaRequest of this S3BucketQuotaRequest.  # noqa: E501
        :rtype: S3BucketQuotaRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this S3BucketQuotaRequest.


        :return: The enabled of this S3BucketQuotaRequest.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this S3BucketQuotaRequest.


        :param enabled: The enabled of this S3BucketQuotaRequest.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def max_size_kb(self) -> int:
        """Gets the max_size_kb of this S3BucketQuotaRequest.


        :return: The max_size_kb of this S3BucketQuotaRequest.
        :rtype: int
        """
        return self._max_size_kb

    @max_size_kb.setter
    def max_size_kb(self, max_size_kb: int):
        """Sets the max_size_kb of this S3BucketQuotaRequest.


        :param max_size_kb: The max_size_kb of this S3BucketQuotaRequest.
        :type max_size_kb: int
        """

        self._max_size_kb = max_size_kb

    @property
    def max_objects(self) -> int:
        """Gets the max_objects of this S3BucketQuotaRequest.


        :return: The max_objects of this S3BucketQuotaRequest.
        :rtype: int
        """
        return self._max_objects

    @max_objects.setter
    def max_objects(self, max_objects: int):
        """Sets the max_objects of this S3BucketQuotaRequest.


        :param max_objects: The max_objects of this S3BucketQuotaRequest.
        :type max_objects: int
        """

        self._max_objects = max_objects
