from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class S3BucketVersioningRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None):  # noqa: E501
        """S3BucketVersioningRequest - a model defined in OpenAPI

        :param status: The status of this S3BucketVersioningRequest.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'status': str
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'S3BucketVersioningRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3BucketVersioningRequest of this S3BucketVersioningRequest.  # noqa: E501
        :rtype: S3BucketVersioningRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this S3BucketVersioningRequest.


        :return: The status of this S3BucketVersioningRequest.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this S3BucketVersioningRequest.


        :param status: The status of this S3BucketVersioningRequest.
        :type status: str
        """
        allowed_values = ["Enabled", "Suspended", "Disabled"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
