from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class S3KeyPair(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, access_key=None, secret_key=None, status=None):  # noqa: E501
        """S3KeyPair - a model defined in OpenAPI

        :param user: The user of this S3KeyPair.  # noqa: E501
        :type user: str
        :param access_key: The access_key of this S3KeyPair.  # noqa: E501
        :type access_key: str
        :param secret_key: The secret_key of this S3KeyPair.  # noqa: E501
        :type secret_key: str
        :param status: The status of this S3KeyPair.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'user': str,
            'access_key': str,
            'secret_key': str,
            'status': str
        }

        self.attribute_map = {
            'user': 'user',
            'access_key': 'access_key',
            'secret_key': 'secret_key',
            'status': 'status'
        }

        self._user = user
        self._access_key = access_key
        self._secret_key = secret_key
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'S3KeyPair':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3KeyPair of this S3KeyPair.  # noqa: E501
        :rtype: S3KeyPair
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this S3KeyPair.


        :return: The user of this S3KeyPair.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this S3KeyPair.


        :param user: The user of this S3KeyPair.
        :type user: str
        """

        self._user = user

    @property
    def access_key(self) -> str:
        """Gets the access_key of this S3KeyPair.


        :return: The access_key of this S3KeyPair.
        :rtype: str
        """
        return self._access_key

    @access_key.setter
    def access_key(self, access_key: str):
        """Sets the access_key of this S3KeyPair.


        :param access_key: The access_key of this S3KeyPair.
        :type access_key: str
        """

        self._access_key = access_key

    @property
    def secret_key(self) -> str:
        """Gets the secret_key of this S3KeyPair.


        :return: The secret_key of this S3KeyPair.
        :rtype: str
        """
        return self._secret_key

    @secret_key.setter
    def secret_key(self, secret_key: str):
        """Sets the secret_key of this S3KeyPair.


        :param secret_key: The secret_key of this S3KeyPair.
        :type secret_key: str
        """

        self._secret_key = secret_key

    @property
    def status(self) -> str:
        """Gets the status of this S3KeyPair.


        :return: The status of this S3KeyPair.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this S3KeyPair.


        :param status: The status of this S3KeyPair.
        :type status: str
        """

        self._status = status
