from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server.models.s3_quota_entry import S3QuotaEntry
from fabric_ceph.openapi_server import util

from fabric_ceph.openapi_server.models.s3_quota_entry import S3QuotaEntry  # noqa: E501

class S3Quota(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_quota=None, bucket_quota=None):  # noqa: E501
        """S3Quota - a model defined in OpenAPI

        :param user_quota: The user_quota of this S3Quota.  # noqa: E501
        :type user_quota: S3QuotaEntry
        :param bucket_quota: The bucket_quota of this S3Quota.  # noqa: E501
        :type bucket_quota: S3QuotaEntry
        """
        self.openapi_types = {
            'user_quota': S3QuotaEntry,
            'bucket_quota': S3QuotaEntry
        }

        self.attribute_map = {
            'user_quota': 'user_quota',
            'bucket_quota': 'bucket_quota'
        }

        self._user_quota = user_quota
        self._bucket_quota = bucket_quota

    @classmethod
    def from_dict(cls, dikt) -> 'S3Quota':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3Quota of this S3Quota.  # noqa: E501
        :rtype: S3Quota
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_quota(self) -> S3QuotaEntry:
        """Gets the user_quota of this S3Quota.


        :return: The user_quota of this S3Quota.
        :rtype: S3QuotaEntry
        """
        return self._user_quota

    @user_quota.setter
    def user_quota(self, user_quota: S3QuotaEntry):
        """Sets the user_quota of this S3Quota.


        :param user_quota: The user_quota of this S3Quota.
        :type user_quota: S3QuotaEntry
        """

        self._user_quota = user_quota

    @property
    def bucket_quota(self) -> S3QuotaEntry:
        """Gets the bucket_quota of this S3Quota.


        :return: The bucket_quota of this S3Quota.
        :rtype: S3QuotaEntry
        """
        return self._bucket_quota

    @bucket_quota.setter
    def bucket_quota(self, bucket_quota: S3QuotaEntry):
        """Sets the bucket_quota of this S3Quota.


        :param bucket_quota: The bucket_quota of this S3Quota.
        :type bucket_quota: S3QuotaEntry
        """

        self._bucket_quota = bucket_quota
