from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class S3UserCapsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, perm=None):  # noqa: E501
        """S3UserCapsInner - a model defined in OpenAPI

        :param type: The type of this S3UserCapsInner.  # noqa: E501
        :type type: str
        :param perm: The perm of this S3UserCapsInner.  # noqa: E501
        :type perm: str
        """
        self.openapi_types = {
            'type': str,
            'perm': str
        }

        self.attribute_map = {
            'type': 'type',
            'perm': 'perm'
        }

        self._type = type
        self._perm = perm

    @classmethod
    def from_dict(cls, dikt) -> 'S3UserCapsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3User_caps_inner of this S3UserCapsInner.  # noqa: E501
        :rtype: S3UserCapsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this S3UserCapsInner.


        :return: The type of this S3UserCapsInner.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this S3UserCapsInner.


        :param type: The type of this S3UserCapsInner.
        :type type: str
        """

        self._type = type

    @property
    def perm(self) -> str:
        """Gets the perm of this S3UserCapsInner.


        :return: The perm of this S3UserCapsInner.
        :rtype: str
        """
        return self._perm

    @perm.setter
    def perm(self, perm: str):
        """Sets the perm of this S3UserCapsInner.


        :param perm: The perm of this S3UserCapsInner.
        :type perm: str
        """

        self._perm = perm
