from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server.models.s3_key_pair import S3KeyPair
from fabric_ceph.openapi_server.models.s3_quota_entry import S3QuotaEntry
from fabric_ceph.openapi_server.models.s3_user_caps_inner import S3UserCapsInner
from fabric_ceph.openapi_server import util

from fabric_ceph.openapi_server.models.s3_key_pair import S3KeyPair  # noqa: E501
from fabric_ceph.openapi_server.models.s3_quota_entry import S3QuotaEntry  # noqa: E501
from fabric_ceph.openapi_server.models.s3_user_caps_inner import S3UserCapsInner  # noqa: E501

class S3User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uid=None, display_name=None, email=None, max_buckets=None, suspended=False, caps=None, keys=None, user_quota=None, bucket_quota=None, system=False, op_mask=None):  # noqa: E501
        """S3User - a model defined in OpenAPI

        :param uid: The uid of this S3User.  # noqa: E501
        :type uid: str
        :param display_name: The display_name of this S3User.  # noqa: E501
        :type display_name: str
        :param email: The email of this S3User.  # noqa: E501
        :type email: str
        :param max_buckets: The max_buckets of this S3User.  # noqa: E501
        :type max_buckets: int
        :param suspended: The suspended of this S3User.  # noqa: E501
        :type suspended: bool
        :param caps: The caps of this S3User.  # noqa: E501
        :type caps: List[S3UserCapsInner]
        :param keys: The keys of this S3User.  # noqa: E501
        :type keys: List[S3KeyPair]
        :param user_quota: The user_quota of this S3User.  # noqa: E501
        :type user_quota: S3QuotaEntry
        :param bucket_quota: The bucket_quota of this S3User.  # noqa: E501
        :type bucket_quota: S3QuotaEntry
        :param system: The system of this S3User.  # noqa: E501
        :type system: bool
        :param op_mask: The op_mask of this S3User.  # noqa: E501
        :type op_mask: str
        """
        self.openapi_types = {
            'uid': str,
            'display_name': str,
            'email': str,
            'max_buckets': int,
            'suspended': bool,
            'caps': List[S3UserCapsInner],
            'keys': List[S3KeyPair],
            'user_quota': S3QuotaEntry,
            'bucket_quota': S3QuotaEntry,
            'system': bool,
            'op_mask': str
        }

        self.attribute_map = {
            'uid': 'uid',
            'display_name': 'display_name',
            'email': 'email',
            'max_buckets': 'max_buckets',
            'suspended': 'suspended',
            'caps': 'caps',
            'keys': 'keys',
            'user_quota': 'user_quota',
            'bucket_quota': 'bucket_quota',
            'system': 'system',
            'op_mask': 'op_mask'
        }

        self._uid = uid
        self._display_name = display_name
        self._email = email
        self._max_buckets = max_buckets
        self._suspended = suspended
        self._caps = caps
        self._keys = keys
        self._user_quota = user_quota
        self._bucket_quota = bucket_quota
        self._system = system
        self._op_mask = op_mask

    @classmethod
    def from_dict(cls, dikt) -> 'S3User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S3User of this S3User.  # noqa: E501
        :rtype: S3User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> str:
        """Gets the uid of this S3User.


        :return: The uid of this S3User.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this S3User.


        :param uid: The uid of this S3User.
        :type uid: str
        """

        self._uid = uid

    @property
    def display_name(self) -> str:
        """Gets the display_name of this S3User.


        :return: The display_name of this S3User.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this S3User.


        :param display_name: The display_name of this S3User.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def email(self) -> str:
        """Gets the email of this S3User.


        :return: The email of this S3User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this S3User.


        :param email: The email of this S3User.
        :type email: str
        """

        self._email = email

    @property
    def max_buckets(self) -> int:
        """Gets the max_buckets of this S3User.


        :return: The max_buckets of this S3User.
        :rtype: int
        """
        return self._max_buckets

    @max_buckets.setter
    def max_buckets(self, max_buckets: int):
        """Sets the max_buckets of this S3User.


        :param max_buckets: The max_buckets of this S3User.
        :type max_buckets: int
        """

        self._max_buckets = max_buckets

    @property
    def suspended(self) -> bool:
        """Gets the suspended of this S3User.


        :return: The suspended of this S3User.
        :rtype: bool
        """
        return self._suspended

    @suspended.setter
    def suspended(self, suspended: bool):
        """Sets the suspended of this S3User.


        :param suspended: The suspended of this S3User.
        :type suspended: bool
        """

        self._suspended = suspended

    @property
    def caps(self) -> List[S3UserCapsInner]:
        """Gets the caps of this S3User.

        RGW admin caps (if enabled); not IAM  # noqa: E501

        :return: The caps of this S3User.
        :rtype: List[S3UserCapsInner]
        """
        return self._caps

    @caps.setter
    def caps(self, caps: List[S3UserCapsInner]):
        """Sets the caps of this S3User.

        RGW admin caps (if enabled); not IAM  # noqa: E501

        :param caps: The caps of this S3User.
        :type caps: List[S3UserCapsInner]
        """

        self._caps = caps

    @property
    def keys(self) -> List[S3KeyPair]:
        """Gets the keys of this S3User.


        :return: The keys of this S3User.
        :rtype: List[S3KeyPair]
        """
        return self._keys

    @keys.setter
    def keys(self, keys: List[S3KeyPair]):
        """Sets the keys of this S3User.


        :param keys: The keys of this S3User.
        :type keys: List[S3KeyPair]
        """

        self._keys = keys

    @property
    def user_quota(self) -> S3QuotaEntry:
        """Gets the user_quota of this S3User.


        :return: The user_quota of this S3User.
        :rtype: S3QuotaEntry
        """
        return self._user_quota

    @user_quota.setter
    def user_quota(self, user_quota: S3QuotaEntry):
        """Sets the user_quota of this S3User.


        :param user_quota: The user_quota of this S3User.
        :type user_quota: S3QuotaEntry
        """

        self._user_quota = user_quota

    @property
    def bucket_quota(self) -> S3QuotaEntry:
        """Gets the bucket_quota of this S3User.


        :return: The bucket_quota of this S3User.
        :rtype: S3QuotaEntry
        """
        return self._bucket_quota

    @bucket_quota.setter
    def bucket_quota(self, bucket_quota: S3QuotaEntry):
        """Sets the bucket_quota of this S3User.


        :param bucket_quota: The bucket_quota of this S3User.
        :type bucket_quota: S3QuotaEntry
        """

        self._bucket_quota = bucket_quota

    @property
    def system(self) -> bool:
        """Gets the system of this S3User.


        :return: The system of this S3User.
        :rtype: bool
        """
        return self._system

    @system.setter
    def system(self, system: bool):
        """Sets the system of this S3User.


        :param system: The system of this S3User.
        :type system: bool
        """

        self._system = system

    @property
    def op_mask(self) -> str:
        """Gets the op_mask of this S3User.


        :return: The op_mask of this S3User.
        :rtype: str
        """
        return self._op_mask

    @op_mask.setter
    def op_mask(self, op_mask: str):
        """Sets the op_mask of this S3User.


        :param op_mask: The op_mask of this S3User.
        :type op_mask: str
        """

        self._op_mask = op_mask
