from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class SubvolumeGroupSummary(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, group_name=None, path=None):  # noqa: E501
        """SubvolumeGroupSummary - a model defined in OpenAPI

        :param group_name: The group_name of this SubvolumeGroupSummary.  # noqa: E501
        :type group_name: str
        :param path: The path of this SubvolumeGroupSummary.  # noqa: E501
        :type path: str
        """
        self.openapi_types = {
            'group_name': str,
            'path': str
        }

        self.attribute_map = {
            'group_name': 'group_name',
            'path': 'path'
        }

        self._group_name = group_name
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'SubvolumeGroupSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubvolumeGroupSummary of this SubvolumeGroupSummary.  # noqa: E501
        :rtype: SubvolumeGroupSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_name(self) -> str:
        """Gets the group_name of this SubvolumeGroupSummary.


        :return: The group_name of this SubvolumeGroupSummary.
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name: str):
        """Sets the group_name of this SubvolumeGroupSummary.


        :param group_name: The group_name of this SubvolumeGroupSummary.
        :type group_name: str
        """

        self._group_name = group_name

    @property
    def path(self) -> str:
        """Gets the path of this SubvolumeGroupSummary.


        :return: The path of this SubvolumeGroupSummary.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this SubvolumeGroupSummary.


        :param path: The path of this SubvolumeGroupSummary.
        :type path: str
        """

        self._path = path
