from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server.models.subvolume_group_list_all_of_data import SubvolumeGroupListAllOfData
from fabric_ceph.openapi_server import util

from fabric_ceph.openapi_server.models.subvolume_group_list_all_of_data import SubvolumeGroupListAllOfData  # noqa: E501

class SubvolumeGroupList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, limit=None, offset=None, size=None, status=200, total=None, type=None, data=None):  # noqa: E501
        """SubvolumeGroupList - a model defined in OpenAPI

        :param limit: The limit of this SubvolumeGroupList.  # noqa: E501
        :type limit: int
        :param offset: The offset of this SubvolumeGroupList.  # noqa: E501
        :type offset: int
        :param size: The size of this SubvolumeGroupList.  # noqa: E501
        :type size: int
        :param status: The status of this SubvolumeGroupList.  # noqa: E501
        :type status: int
        :param total: The total of this SubvolumeGroupList.  # noqa: E501
        :type total: int
        :param type: The type of this SubvolumeGroupList.  # noqa: E501
        :type type: str
        :param data: The data of this SubvolumeGroupList.  # noqa: E501
        :type data: List[SubvolumeGroupListAllOfData]
        """
        self.openapi_types = {
            'limit': int,
            'offset': int,
            'size': int,
            'status': int,
            'total': int,
            'type': str,
            'data': List[SubvolumeGroupListAllOfData]
        }

        self.attribute_map = {
            'limit': 'limit',
            'offset': 'offset',
            'size': 'size',
            'status': 'status',
            'total': 'total',
            'type': 'type',
            'data': 'data'
        }

        self._limit = limit
        self._offset = offset
        self._size = size
        self._status = status
        self._total = total
        self._type = type
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SubvolumeGroupList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubvolumeGroupList of this SubvolumeGroupList.  # noqa: E501
        :rtype: SubvolumeGroupList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def limit(self) -> int:
        """Gets the limit of this SubvolumeGroupList.


        :return: The limit of this SubvolumeGroupList.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this SubvolumeGroupList.


        :param limit: The limit of this SubvolumeGroupList.
        :type limit: int
        """

        self._limit = limit

    @property
    def offset(self) -> int:
        """Gets the offset of this SubvolumeGroupList.


        :return: The offset of this SubvolumeGroupList.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this SubvolumeGroupList.


        :param offset: The offset of this SubvolumeGroupList.
        :type offset: int
        """

        self._offset = offset

    @property
    def size(self) -> int:
        """Gets the size of this SubvolumeGroupList.


        :return: The size of this SubvolumeGroupList.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this SubvolumeGroupList.


        :param size: The size of this SubvolumeGroupList.
        :type size: int
        """

        self._size = size

    @property
    def status(self) -> int:
        """Gets the status of this SubvolumeGroupList.


        :return: The status of this SubvolumeGroupList.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this SubvolumeGroupList.


        :param status: The status of this SubvolumeGroupList.
        :type status: int
        """

        self._status = status

    @property
    def total(self) -> int:
        """Gets the total of this SubvolumeGroupList.


        :return: The total of this SubvolumeGroupList.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this SubvolumeGroupList.


        :param total: The total of this SubvolumeGroupList.
        :type total: int
        """

        self._total = total

    @property
    def type(self) -> str:
        """Gets the type of this SubvolumeGroupList.


        :return: The type of this SubvolumeGroupList.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this SubvolumeGroupList.


        :param type: The type of this SubvolumeGroupList.
        :type type: str
        """

        self._type = type

    @property
    def data(self) -> List[SubvolumeGroupListAllOfData]:
        """Gets the data of this SubvolumeGroupList.

        When `info=false`, items are names (strings). When `info=true`, items may be detailed objects.   # noqa: E501

        :return: The data of this SubvolumeGroupList.
        :rtype: List[SubvolumeGroupListAllOfData]
        """
        return self._data

    @data.setter
    def data(self, data: List[SubvolumeGroupListAllOfData]):
        """Sets the data of this SubvolumeGroupList.

        When `info=false`, items are names (strings). When `info=true`, items may be detailed objects.   # noqa: E501

        :param data: The data of this SubvolumeGroupList.
        :type data: List[SubvolumeGroupListAllOfData]
        """

        self._data = data
