from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server import util


class SubvolumeSummary(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, group_name=None, path=None, bytes_quota=None, bytes_used=None, state=None):  # noqa: E501
        """SubvolumeSummary - a model defined in OpenAPI

        :param name: The name of this SubvolumeSummary.  # noqa: E501
        :type name: str
        :param group_name: The group_name of this SubvolumeSummary.  # noqa: E501
        :type group_name: str
        :param path: The path of this SubvolumeSummary.  # noqa: E501
        :type path: str
        :param bytes_quota: The bytes_quota of this SubvolumeSummary.  # noqa: E501
        :type bytes_quota: int
        :param bytes_used: The bytes_used of this SubvolumeSummary.  # noqa: E501
        :type bytes_used: int
        :param state: The state of this SubvolumeSummary.  # noqa: E501
        :type state: str
        """
        self.openapi_types = {
            'name': str,
            'group_name': str,
            'path': str,
            'bytes_quota': int,
            'bytes_used': int,
            'state': str
        }

        self.attribute_map = {
            'name': 'name',
            'group_name': 'group_name',
            'path': 'path',
            'bytes_quota': 'bytes_quota',
            'bytes_used': 'bytes_used',
            'state': 'state'
        }

        self._name = name
        self._group_name = group_name
        self._path = path
        self._bytes_quota = bytes_quota
        self._bytes_used = bytes_used
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'SubvolumeSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubvolumeSummary of this SubvolumeSummary.  # noqa: E501
        :rtype: SubvolumeSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this SubvolumeSummary.


        :return: The name of this SubvolumeSummary.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SubvolumeSummary.


        :param name: The name of this SubvolumeSummary.
        :type name: str
        """

        self._name = name

    @property
    def group_name(self) -> str:
        """Gets the group_name of this SubvolumeSummary.


        :return: The group_name of this SubvolumeSummary.
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name: str):
        """Sets the group_name of this SubvolumeSummary.


        :param group_name: The group_name of this SubvolumeSummary.
        :type group_name: str
        """

        self._group_name = group_name

    @property
    def path(self) -> str:
        """Gets the path of this SubvolumeSummary.


        :return: The path of this SubvolumeSummary.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this SubvolumeSummary.


        :param path: The path of this SubvolumeSummary.
        :type path: str
        """

        self._path = path

    @property
    def bytes_quota(self) -> int:
        """Gets the bytes_quota of this SubvolumeSummary.


        :return: The bytes_quota of this SubvolumeSummary.
        :rtype: int
        """
        return self._bytes_quota

    @bytes_quota.setter
    def bytes_quota(self, bytes_quota: int):
        """Sets the bytes_quota of this SubvolumeSummary.


        :param bytes_quota: The bytes_quota of this SubvolumeSummary.
        :type bytes_quota: int
        """

        self._bytes_quota = bytes_quota

    @property
    def bytes_used(self) -> int:
        """Gets the bytes_used of this SubvolumeSummary.


        :return: The bytes_used of this SubvolumeSummary.
        :rtype: int
        """
        return self._bytes_used

    @bytes_used.setter
    def bytes_used(self, bytes_used: int):
        """Sets the bytes_used of this SubvolumeSummary.


        :param bytes_used: The bytes_used of this SubvolumeSummary.
        :type bytes_used: int
        """

        self._bytes_used = bytes_used

    @property
    def state(self) -> str:
        """Gets the state of this SubvolumeSummary.


        :return: The state of this SubvolumeSummary.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this SubvolumeSummary.


        :param state: The state of this SubvolumeSummary.
        :type state: str
        """

        self._state = state
