from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_ceph.openapi_server.models.base_model import Model
from fabric_ceph.openapi_server.models.capability_kv import CapabilityKV
from fabric_ceph.openapi_server import util

from fabric_ceph.openapi_server.models.capability_kv import CapabilityKV  # noqa: E501

class UpdateUserCapsRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_entity=None, capabilities=None):  # noqa: E501
        """UpdateUserCapsRequest - a model defined in OpenAPI

        :param user_entity: The user_entity of this UpdateUserCapsRequest.  # noqa: E501
        :type user_entity: str
        :param capabilities: The capabilities of this UpdateUserCapsRequest.  # noqa: E501
        :type capabilities: List[CapabilityKV]
        """
        self.openapi_types = {
            'user_entity': str,
            'capabilities': List[CapabilityKV]
        }

        self.attribute_map = {
            'user_entity': 'user_entity',
            'capabilities': 'capabilities'
        }

        self._user_entity = user_entity
        self._capabilities = capabilities

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateUserCapsRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateUserCapsRequest of this UpdateUserCapsRequest.  # noqa: E501
        :rtype: UpdateUserCapsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_entity(self) -> str:
        """Gets the user_entity of this UpdateUserCapsRequest.


        :return: The user_entity of this UpdateUserCapsRequest.
        :rtype: str
        """
        return self._user_entity

    @user_entity.setter
    def user_entity(self, user_entity: str):
        """Sets the user_entity of this UpdateUserCapsRequest.


        :param user_entity: The user_entity of this UpdateUserCapsRequest.
        :type user_entity: str
        """
        if user_entity is None:
            raise ValueError("Invalid value for `user_entity`, must not be `None`")  # noqa: E501

        self._user_entity = user_entity

    @property
    def capabilities(self) -> List[CapabilityKV]:
        """Gets the capabilities of this UpdateUserCapsRequest.

        Complete set of caps to apply (overwrites existing). Provide one entry per component.   # noqa: E501

        :return: The capabilities of this UpdateUserCapsRequest.
        :rtype: List[CapabilityKV]
        """
        return self._capabilities

    @capabilities.setter
    def capabilities(self, capabilities: List[CapabilityKV]):
        """Sets the capabilities of this UpdateUserCapsRequest.

        Complete set of caps to apply (overwrites existing). Provide one entry per component.   # noqa: E501

        :param capabilities: The capabilities of this UpdateUserCapsRequest.
        :type capabilities: List[CapabilityKV]
        """
        if capabilities is None:
            raise ValueError("Invalid value for `capabilities`, must not be `None`")  # noqa: E501

        self._capabilities = capabilities
